# Generated by Django 4.1.7 on 2023-02-27 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('title', models.CharField(default='Doctor', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=20)),
                ('code', models.CharField(max_length=7)),
                ('street', models.CharField(max_length=20)),
                ('houseNo', models.CharField(max_length=2)),
                ('apartNo', models.CharField(max_length=2)),
                ('commune', models.CharField(max_length=20)),
                ('voivodeship', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('pesel', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('birth', models.DateField(null=True)),
                ('phoneNo', models.CharField(max_length=12)),
                ('NIP', models.CharField(max_length=10, null=True)),
                ('healthNo', models.CharField(max_length=20, null=True)),
                ('added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('phoneNo', models.CharField(max_length=12)),
                ('NIP', models.CharField(max_length=10)),
                ('REGON', models.CharField(max_length=9)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.account', verbose_name='Owner')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.clinic')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.patient')),
            ],
        ),
    ]
