# Generated by Django 4.1.7 on 2023-02-28 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_alter_patient_nip_alter_patient_birth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='NIP',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='added',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='birth',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='healthNo',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='phoneNo',
        ),
    ]
